# Generated by Django 5.1 on 2024-12-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_registeration_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeration',
            name='isActive',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='otp',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
