# Generated by Django 5.1 on 2024-12-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_registeration_isactive_alter_registeration_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
