# Generated by Django 5.1 on 2024-12-29 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_animalbreed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Behavior', models.CharField(max_length=20)),
                ('Animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.animal')),
            ],
        ),
    ]
