# Generated by Django 5.1 on 2024-12-31 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_petadopter'),
    ]

    operations = [
        migrations.AddField(
            model_name='petadopter',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.registeration'),
        ),
    ]
