# Generated by Django 5.1 on 2024-12-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_petadopter_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='addedpets',
            name='Available',
            field=models.BooleanField(default=True),
        ),
    ]
